### ISSUE TITLE
Porting version for Intellij IDEs

### ISSUE THREAD

**Issue by Happin3ss** [sainnhe/gruvbox-material-vscode#14]
Hi, I really love this theme so I'm trying to port it into Jetbrains IDE. I normally use both VSCode and IDEA so It's great to have both of them on the same color scheme.
 I made an init version here : https://github.com/Happin3ss/gruvbox-material
 Contributions are welcome :) . This is the first time I deal with this kind of stuffs so It might take weeks to have first release version.

**Comment by sainnhe** [comment]
Great work!

I mainly use vim and sometimes use vscode, so I may not be able to contribute code, very sorry.

I found 2 existing ports of gruvbox, maybe you can refer to their code:

- [caleb/gruvbox-idea](https://github.com/caleb/gruvbox-idea)
- [Vincent-P/gruvbox-intellij-theme](https://github.com/Vincent-P/gruvbox-intellij-theme)

In addition, do you mind if I add your project to [Related Projects](https://github.com/sainnhe/gruvbox-material#related-projects)? This way others can see your project from there.

**Comment by Happin3ss** [comment]
Hi, thanks for the reference, I will have a look on it.
Regards to related projects, definitely ! Might some people can help to speed up the work. But please make it clearly it still in-progress and not yet available :)  Thank you !

**Comment by sainnhe** [comment]
So I added the URL to related projects. If you are ready to release the first version, please tell me so I will remove the `WIP` tag.

If you do need others' help, you can contact other developers of intellij plugins or create a new post [here](https://intellij-support.jetbrains.com/hc/en-us/community/topics).

I'm going to close this issue since it's unrelated to vscode. If you have any problem in porting, please open an issue in [sainnhe/gruvbox-material](https://github.com/sainnhe/gruvbox-material/issues) instead.
