### ISSUE TITLE
Some keywords becomes colorless in the recent versions

### ISSUE THREAD

**Issue by antfu** [sainnhe/gruvbox-material-vscode#15]
This is my favorite theme and I have used it for about a year! Thanks for your great work.

But in the recent versions, some keywords becomes colorless:
![image](https://user-images.githubusercontent.com/11247099/79446770-61b0d680-8011-11ea-8888-6260609e1cda.png)

The left side is v6.0.4. And the right side is v4.2.0. LanguageID: `typescript`

I really like the borderless look in the new versions but this issue prevents me to switch to it. 

Is there anything I can do to fix this? Thanks!

**Comment by sainnhe** [comment]
That's intentional, the syntax highlighting logic has been redesigned since v5.0.0 [#10](https://github.com/sainnhe/gruvbox-material-vscode/issues/10#issuecomment-576482535).

But thanks for your reminding, the original syntax highlighting logic should not be discarded hastily. I've added a new configuration option to enable the original syntax highlighting logic 2318e30.

**Comment by sainnhe** [comment]
It's renamed as `gruvboxMaterial.colorfulSyntax` now.

**Comment by antfu** [comment]
Thanks for the quick reply!  I have checked it out and I love it. Thank you!
