### ISSUE TITLE
Explorer file names colorization

### ISSUE THREAD

**Issue by Z4RX** [sainnhe/gruvbox-material-vscode#20]
Can You add some settings for explorer file names colorization? For me it looks too pale and sadly I'm noob and don't know how to fix it.
![image](https://user-images.githubusercontent.com/58516282/80757171-66f74080-8b3c-11ea-99cf-b3c802a41b77.png)

**Comment by sainnhe** [comment]
The color of file name is designed to be grey in order to help developers focus on their code, as well as the status bar, the title bar and the activity bar.

Sorry but I can't see the necessity of this setting.

A color scheme cannot make everyone feel perfect. If you want to customize some workbench colors, you can adjust them in your user settings instead. See [this article](https://dev.to/tluanga34/customize-visual-studio-code-ui-colors-on-top-of-a-theme-4jm0) for more information.

**Comment by Z4RX** [comment]
thx for Your answer. It helped.
