### ISSUE TITLE
[C++] Enhanced colorization by vscode-cpptools

### ISSUE THREAD

**Issue by Z4RX** [sainnhe/gruvbox-material-vscode#28]
Micrisoft [C/C++](https://github.com/Microsoft/vscode-cpptools) extension gives enchanced colorization which brokes theme's one.
I think it should be disabled. But I don't know how to do it, so need your help @sainnhe 
Example:
![image](https://user-images.githubusercontent.com/58516282/86809340-733fd280-c084-11ea-9c64-634b405ba904.png)

**Comment by Z4RX** [comment]
I found similar issue [here](https://github.com/Binaryify/OneDark-Pro/issues/395)

[Binaryify](https://github.com/Binaryify) wrote that add this line `"C_Cpp.enhancedColorization": "Disabled"` into settings.json is enough

**Comment by sainnhe** [comment]
I've added an [FAQ](https://github.com/sainnhe/gruvbox-material-vscode#faq) for disabling semantic highlighting.

Btw, I think the frequency of releasing new versions is too high, we've released 6 new versions in the past 20 days.

Let's only release a new version only when it is more than one month since the last release, unless there's a very serious bug or a new feature. Generally, when a bug has been fixed, users should compile from source to get the latest update, I've updated the [installation guide](https://github.com/sainnhe/gruvbox-material-vscode/commit/3968c3bd831c78ce3a06b35f833c4b50fdc119a8).

Btw, the json file will be generated automatically before committing your changes, I've added a new [pre-commit hook](https://github.com/sainnhe/gruvbox-material-vscode/tree/master/src/hook) to do this.

**Comment by Z4RX** [comment]
It's not a semantic semantic highlighting. It's about enchanced syntaxes by an extansion as it was with babel js.

Ok!

**Comment by sainnhe** [comment]
According to [the doc](https://code.visualstudio.com/docs/cpp/colorization-cpp):

> The Visual Studio Code C/C++ extension now supports semantic colorization, when IntelliSense is enabled. Use of enhanced colorization is controlled by the C_Cpp.enhancedColorization setting. This setting is enabled by default.

If the enhanced highlighting is powered by semantic highlighting, I think we can use `editor.semanticHighlighting.enabled` to disable it, but I haven't tested it yet.

**Comment by Z4RX** [comment]
This extencion modifies even without semantic.
Probably we can add this `"C_Cpp.enhancedColorization": "Disabled"` to theme json file
![image](https://user-images.githubusercontent.com/58516282/87219394-48df6500-c363-11ea-867f-c0ff319cb940.png)
![image](https://user-images.githubusercontent.com/58516282/87219400-598fdb00-c363-11ea-899b-2bdaa373d328.png)

**Comment by Z4RX** [comment]
[OFFTOP] In python true//false looks not simillar to other languages and vim theme. Is it bug?
![image](https://user-images.githubusercontent.com/58516282/87220259-face5f80-c36a-11ea-986f-75927f2f6c4a.png)

**Comment by sainnhe** [comment]
I've updated the FAQ via cbe8493

No, the fg of constant like `None`, `True` is designed to be aqua.

**Comment by Z4RX** [comment]
I researched this question and find probable solution.
add this code to `settings.json` will fix this issue (need time to test)
`            {
                "scope": "entity.name.function.operator",
                "settings": {
                    "foreground": "#E78A4E"
                }
            }` 
here is an [article](https://code.visualstudio.com/docs/cpp/colorization-cpp) about new tokens.

Can we check in theme TS which extensions are active?

**Comment by sainnhe** [comment]
> Can we check in theme TS which extensions are active?

I'm not sure if it's possible, you can search for available apis [here](https://code.visualstudio.com/api/references/vscode-api).

Btw, have you check your gmail? There's some updates in development process.

**Comment by Z4RX** [comment]
yes, I did.

Thx, i ll try find the solution.

**Comment by Z4RX** [comment]
Looks like there is no issues with proposed fix, i think we can add it to theme without checking active extensions because it looks like this token is used by c_cpp extension only


I ll fix problems with nodejs on my machine and will publish new version with some fixes soon

**Comment by sainnhe** [comment]
That's nice.

**Comment by Z4RX** [comment]
@sainnhe edit FAQ pls. Now we I think that we should reccomend to use [C/C++](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) and not to use colorfull syntax with this language at all.

**Comment by sainnhe** [comment]
> @sainnhe edit FAQ pls. Now I think that we should reccomend to use [C/C++](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) and not to use colorfull syntax with this language at all.

I was thought that anyone should not use this theme with babel javascript extension, and even considered for making this theme conflict with babel javascript, because I think babel is much worse than the built-in javascript syntax highlighting (I still think so at this moment, you can search for related issues in this repo).

But now, I think the better solution should be trying my best to make this theme work better with these extensions.

Therefore, I think we should not add any doc to tell users not to use this or that extension. If they encountered any problem, they'll search for issues and get a solution.
