### ISSUE TITLE
Enhanced colorization by extensions

### ISSUE THREAD

**Issue by Z4RX** [sainnhe/gruvbox-material-vscode#30]
For example [django ext](https://marketplace.visualstudio.com/items?itemName=batisteo.vscode-django) add new scopes for django templates and smtg like this. Probably we should add into **_FAQ_** or **_wiki_** smtg like `supported extensions` or `recommended extensions`. We can add support for the most popular extensions which add some special scopes. There are no issues with special scopes, cuz editor will ignore them without extensions.

This task looks similar to supporting semantic.

**Comment by sainnhe** [comment]
This is what I have done in the [earlier version](https://github.com/sainnhe/gruvbox-material-vscode/tree/v2.0.0).

Honestly I think it's not a good idea to list them in readme like this, because as you can see, there're too many optimized extensions (about 50+) which may confuse users.

But that's necessary, there SHOULD be a list to tell users which extension is recommended and which is not. The better solution might be creating a wiki page and add a link to it in the readme.

I'll do it later.

**Comment by sainnhe** [comment]
Done in v6.3.0, you can see all supported file types and syntax extensions in [Features](https://github.com/sainnhe/gruvbox-material-vscode#features).

If you've optimized any syntax extension, you can add it in readme.
