### ISSUE TITLE
Feature Request: Add a custom error/warning background color

### ISSUE THREAD

**Issue by eduardocanellas** [sainnhe/gruvbox-material-vscode#44]
Hello! In VS Code 1.52, it's now possible to add a custom background color for errors in the editor. I think that would be a great enhancement. It'll probably be easier to visualize the errors and warnings with a background color to highlight it.

Here's the link to the new VS Code feature: https://code.visualstudio.com/updates/v1_52#_error-background-colors

What do you think? :)

**Comment by or-mandelbrot** [comment]
Guys, please don't take this the wrong way. I have many a fond memory of 36 hour code binges staring at your beautiful, beautiful themes. They have been my redemption in my darkest moments and my grace in those lightest. They have been with me through thick and thin. But if this error highlighting  *ahem* "stuff" is to stay, without the option to disable, then I'm gonna have to put my precious color themes out of their miseries. 

It would break my heart to kill something I love so dearly, but I know I have to be strong. Because true love means that you don't keep those you love around to provide you solace even though they are irrevocably broken. Sometimes, if you love something, you have to let it go. I hope it doesn't come to that. I really do, because I do love your themes. But please, for the love of all that is right, happy, and true: fix this.

**Comment by OrEisenberg** [comment]
Guys, please don't take this the wrong way. I have many a fond memory of 36 hour code binges staring at your beautiful, beautiful themes. They have been my redemption in my darkest moments and my grace in those lightest. They have been with me through thick and thin. But if this error highlighting ahem "stuff" is to stay, without the option to disable, then I'm gonna have to put my precious color themes out of their miseries.

It would break my heart to kill something I love so dearly, but I know I have to be strong. Because true love means that you don't keep those you love around to provide you solace even though they are irrevocably broken. That would be selfish. Sometimes, if you love something, you have to let it go. I hope it doesn't come to that. I really do, because I do love your themes. But please, for the love of all that is right, happy, and true: fix this.

**Comment by koaleksa** [comment]
@OrEisenberg I'd very much like to know.

**Comment by koaleksa** [comment]
Ok, I figured out one workaround, not sure if it's the same as OrEisenberg's but adding these few lines to settings.json will do the trick:

```
    "workbench.colorCustomizations": {
        "[Gruvbox Material Dark]": {
            "editorError.background": "#28282800",
            "editorWarning.background": "#28282800",
            "editorInfo.background": "#28282800",
        },
```

**Comment by sainnhe** [comment]
A new option is introduced in v6.3.6 that can customize the opacity of background colors.
