### ISSUE TITLE
[Improvement] Different color for function parameter in C/C++

### ISSUE THREAD

**Issue by Ahsan40** [sainnhe/gruvbox-material-vscode#50]
First I want to thank you for making such a great theme for vscode and maintaining it regularly. Now the reason I opened this is I have a suggestion for syntax highlighting for C/C++. I saw in many themes that they have different colors for function parameters. Kind of like this,

![image](https://user-images.githubusercontent.com/30434801/116220054-2097ea00-a76e-11eb-9c1a-e82bc3b44a21.png)

As you can here variable `a` and `b` has the same color. Can you make it to different? Or maybe add a setting to do it? like the image below,

![image](https://user-images.githubusercontent.com/30434801/116220384-740a3800-a76e-11eb-84be-de2e5b7992e3.png)

**Comment by sainnhe** [comment]
Sorry but I may not do this. Because there are 7 foreground colors in total, and all of them have been used, which means if I changed the color of different parameters, it will be hard to distinguish between these parameters and some keywords.

As for color schemes, it’s very difficult to make the developers' designs satisfy everyone. I'd recommend you to fork this repository and modify it to be what you prefer. See CONTRIBUTING.md for detailed steps to hack this color scheme.
