### ISSUE TITLE
[FEATURE REQUEST] Add the option to disable italic font on comments

### ISSUE THREAD

**Issue by pedro15** [sainnhe/gruvbox-material-vscode#51]
I don't like much the fact that all the comments are in italic. I wish you add the option to disable/enable this. Thank you!

**Comment by sainnhe** [comment]
1. I am not obligated to fulfill all your needs. You are not my employer and I'm not your employee, I'm only interested in implementing my personal needs and fixing bugs.
2. This is an open source project, if you need something, it's recommended to fork this repository and open a PR.
3. I do understand that sometimes features requests are necessary, but please at least describe why this feature is necessary, instead of just saying "I like foo and I dislike bar".
4. This option already exists.

https://github.com/sainnhe/gruvbox-material-vscode/blob/df2792ea466cb463cfe67cfece0958ad4f49fabf/package.json#L189-L193

**Comment by pedro15** [comment]
> 
> 
>     1. I am not obligated to fulfill all your needs. You are not my employer and I'm not your employee, I'm only interested in implementing my personal needs and fixing bugs.
> 
>     2. This is an open source project, if you need something, it's recommended to fork this repository and open a PR.
> 
>     3. I do understand that sometimes features requests are necessary, but please at least describe why this feature is necessary, instead of just saying "I like foo and I dislike bar".
> 
>     4. This option already exists.
> 
> 
> https://github.com/sainnhe/gruvbox-material-vscode/blob/df2792ea466cb463cfe67cfece0958ad4f49fabf/package.json#L189-L193

Thank you, sorry for the poor explaination during the issue, and thanks again! i just found the option, have a good day!
