### ISSUE TITLE
Color look a bit washed 

### ISSUE THREAD

**Issue by GulajavaMinistudio** [sainnhe/gruvbox-material-vscode#6]
Im trying this theme, but when opening JS files and some HTML file, this syntax coloring looks a bit washed. So it can't be distinguished from other method or object in it. Maybe the coloring needs more vivid or vibrant colors.

You can take a look on screenshot below.
![Screenshot_2019-11-15_14-36-10](https://user-images.githubusercontent.com/11639412/68925444-a364f900-07b5-11ea-8644-5cc88e44aa0c.png)

**Comment by sainnhe** [comment]
What I don't understand is why `meta.object-literal.key.js` is green in your screenshot, this is what it looks like in my vscode:

![origin](https://user-images.githubusercontent.com/37491630/68928411-f85c3b80-07c4-11ea-975e-afd8a1faebd0.png)

But it needs to be tweaked indeed, I made a slight adjustment to it:

![new](https://user-images.githubusercontent.com/37491630/68928548-4a04c600-07c5-11ea-80e1-df3ed647c5ab.png)

What is your vscode version? Have you installed any syntax extensions that might affect the javascript syntax highlighting? This theme is currently only optimized for built-in js syntax highlighting.

**Comment by GulajavaMinistudio** [comment]
I dont know why is different from your screenshot. Im using JavaScript ES6 Snippet and Babel JavaScript extension. My VS Code version is 1.40.0 .

**Comment by sainnhe** [comment]
I've tried [mgmcdermott.vscode-language-babel](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel), it reproduced.

![ext](https://user-images.githubusercontent.com/37491630/68930978-825ad300-07ca-11ea-9f4e-499af04d946b.png)

Sorry but I won't optimize this syntax extension, because I think it's very bad. This is the built-in js syntax highlighting:

![origin](https://user-images.githubusercontent.com/37491630/68931060-b7672580-07ca-11ea-8bfd-92cef338a75e.png)

As you can see, in `mgmcdermott.vscode-language-babel`, the code scope is `string.unquoted.js`, while in the build-in js syntax highlighting, the code scope is `meta.object-literal.key.js`. This means that in `mgmcdermott.vscode-language-babel`, the string is logically related to unquoted string.

In vscode, `string.unquoted.js` inherits from `string.unquoted`, and `string.unquoted` inherits from `string`. I personally think any scopes related to `string` should be green(or maybe white), so the fact that `string.unquoted.js` is green is logical, but it's obviously illogical this case. I guess the author of this extension has put a lot of other code in this scope.

I suggest you uninstall this extension and use build-in js syntax highlighting instead, microsoft has done a very great job in js syntax highlighting. The build-in js syntax highlighting is logical and accurate, and **every** element can be highlighted.

**Comment by GulajavaMinistudio** [comment]
Thanks for response and solution from you.
And one more thing, here some reference for material colors, i think the fit palette is between 500 - 700 . For example Green 500, Red 500, etc

You can check palette in here.
[Material Palette](https://material.io/design/color/#tools-for-picking-colors)

**Comment by sainnhe** [comment]
Thanks for your link.

I have tried to use existing material palettes directly, but the effect is not good. Many material palettes are mainly designed for UI colors instead of foreground colors, so there are some very serious problems when using as foreground colors. To sum up, they're not eye-friendly at all. Please forgive me for saying so straightforward, but this is the truth.

The current color palette has been carefully adjusted many times based on the original gruvbox and has been tested on several devices, and works very well with redshift and f.lux .

But I think it is currently far from perfect, there might be some adjustments in the future. If you have any ideas or suggestions, welcome to share them in [#11](https://github.com/sainnhe/gruvbox-material/issues/11).
